version: '3'
services:
  server:
    build: ./server
    ports:
     - "5000:5000"
  client:
    image: clientv2
    build: ./client
    command: tail -f /dev/null
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
